<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    
<div class="container">
    <div class="mt-5 text-center"><h3>Order Form.</h3></div>

    <h2>Place your Order Here</h2>

        <?php echo $this->tag->form("order/place"); ?>
            <p>
            <?php 
                if(isset($message)){ 
                    echo $message;
                } 
            ?>

        </p>

            <p>
                <label for="name">Custoemer-Name</label>
                <?php echo $this->tag->textField([
                    'name'=>"name",
                    'id'=>"form2Example1",
                    'class'=>"form-control" 
                    ]); ?>
            </p>

            <p>
                <label for="email">Address</label>
                <?php echo $this->tag->TextArea([
                    'name'=>"address",
                    'id'=>"form2Example1",
                    'class'=>"form-control" 
            ]); ?>
            </p>
            <p>
                <label for="email">zipcode</label>
                <?php echo $this->tag->textField([
                    'name'=>"zipcode",
                    'id'=>"form2Example1",
                    'class'=>"form-control" 
            ]); ?>
            </p>

            <p>
                <label for="email"> Quantity</label>
                <?php echo $this->tag->textField([
                    'name'=>"quantity",
                    'id'=>"form2Example1",
                    'class'=>"form-control" 
            ]); ?>
            </p>

            <p>
                <label for="email">Product</label>
                <?php echo $this->tag->select(
                    [
                    "product",
                    [
                        '1'=>'with_key',
                        '2'=>'without_key'
                    ],
                    'class'=>"form-control" 

            ]); ?>
            </p>

            
            <p>
                <?php echo $this->tag->submitButton([
                    "submit",
                    "name"=>"submit",
                    'class'=>"btn btn-primary btn-block mb-4"
                    ]
                    
                    ); ?>
            </p>

        </form>



</div>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</html>